# Generated by Django 4.2.16 on 2024-11-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='Imagenes-Medicos')),
                ('nombre_completo', models.CharField(max_length=255)),
                ('especialidad', models.CharField(max_length=255)),
                ('cmp', models.IntegerField(max_length=20)),
                ('experiencia', models.IntegerField(max_length=20)),
                ('ciudad', models.CharField(max_length=150)),
                ('edad', models.IntegerField(max_length=100)),
                ('telefono', models.IntegerField(max_length=10)),
                ('correo_electronico', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=2)),
            ],
        ),
    ]
