# Generated by Django 4.2.16 on 2024-11-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctormodels',
            name='cmp',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='doctormodels',
            name='edad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='doctormodels',
            name='experiencia',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='doctormodels',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
