# Generated by Django 4.2.16 on 2024-11-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctores', '0004_alter_doctormodels_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspecialidadesModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_especialidad', models.CharField(max_length=155)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Especialidad Médica',
                'verbose_name_plural': 'Especialidades Médicas',
                'ordering': ['nombre_especialidad'],
            },
        ),
    ]
