# Generated by Django 4.2.16 on 2024-11-14 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doctores', '0007_remove_doctormodels_especialidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctormodels',
            name='especialidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Doctores.especialidadesmodels'),
        ),
    ]
