# Generated by Django 4.2.16 on 2024-11-14 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctores', '0009_especialidadesmodels_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidadesmodels',
            name='slug',
            field=models.SlugField(blank=True, default='boli', unique=True),
        ),
    ]
