# Generated by Django 4.2.16 on 2024-11-14 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctores', '0011_alter_especialidadesmodels_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidadesmodels',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
