# Generated by Django 4.2.16 on 2024-11-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctores', '0012_alter_especialidadesmodels_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctormodels',
            name='Genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='doctormodels',
            name='apellido',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctormodels',
            name='numero_documento',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='doctormodels',
            name='tipo_documento',
            field=models.CharField(choices=[('DNI', 'DNI'), ('PASAPORTE', 'Pasaporte'), ('CARNET EXT', 'Carnet de Extranjería')], default='DNI', max_length=11),
        ),
        migrations.AlterField(
            model_name='doctormodels',
            name='telefono',
            field=models.IntegerField(null=123456789),
        ),
        migrations.AlterField(
            model_name='especialidadesmodels',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
